Userinfo endpoint
dextra/dexquiz pull request #17
Opened 2020-09-11 19:44 UTC by g14costa

2020-09-11 19:53 UTC, Gabriel-Cordeiro approved these changes

2020-09-11 22:52 UTC, gustavobigardi approved these changes

2020-09-11 22:52 UTC, gustavobigardi commented
LGTM

2020-09-11 22:53 UTC, gustavobigardi requested changes
We have some files in conflict. Please review them.

2020-09-13 12:49 UTC, gustavobigardi approved these changes

2020-09-13 12:49 UTC, merged